import { api, type AssistantResponse } from "@/lib/api";

const esc = (s: unknown) =>
  String(s ?? "").replace(
    /[&<>"]/g,
    (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[c] as string,
  );

// Open a print-ready window with the company header, the question, Benfieg's
// plain-English answer, the data sources it used (with provenance), and a
// disclaimer. The user picks "Save as PDF" in the print dialog — no PDF library
// needed, matching how invoices are exported.
export async function printReport(r: AssistantResponse) {
  const company = await api.company().catch(() => null);
  const now = new Date();

  const sources = r.tool_calls
    .map(
      (c) =>
        `<li><span class="mono">${esc(c.name)}</span> <span class="tag">${esc(
          c.provenance,
        )}</span></li>`,
    )
    .join("");

  const actions =
    r.actions_taken.length > 0
      ? `<div class="note"><strong>Changes applied:</strong> ${esc(
          r.actions_taken.join(", "),
        )}</div>`
      : "";

  const html = `<!doctype html><html><head><meta charset="utf-8">
<title>Business report — ${esc(now.toLocaleDateString())}</title>
<style>
  * { box-sizing: border-box; }
  body { font: 13px/1.6 -apple-system, Segoe UI, Roboto, sans-serif; color: #111; margin: 32px; }
  header { border-bottom: 2px solid #111; padding-bottom: 12px; margin-bottom: 20px; }
  h1 { font-size: 18px; margin: 0 0 2px; }
  .muted { color: #666; font-size: 11px; }
  h2 { font-size: 13px; text-transform: uppercase; letter-spacing: .05em; color: #444; margin: 22px 0 6px; }
  .q { background: #f4f4f5; border-left: 3px solid #111; padding: 8px 12px; border-radius: 4px; }
  .answer { white-space: pre-wrap; }
  ul { margin: 6px 0; padding-left: 18px; }
  .mono { font-family: ui-monospace, Menlo, monospace; font-size: 11px; }
  .tag { font-size: 9px; text-transform: uppercase; letter-spacing: .04em; border: 1px solid #ccc; border-radius: 999px; padding: 1px 6px; color: #555; }
  .note { background: #ecfdf5; border: 1px solid #a7f3d0; border-radius: 4px; padding: 6px 10px; margin: 12px 0; }
  footer { margin-top: 28px; border-top: 1px solid #ddd; padding-top: 10px; color: #666; font-size: 10px; }
  @media print { body { margin: 16mm; } }
</style></head><body>
<header>
  <h1>${esc(company?.name || "Business report")}</h1>
  <div class="muted">
    ${company?.address ? esc(company.address) + " · " : ""}
    ${company?.phone ? esc(company.phone) + " · " : ""}
    ${company?.email ? esc(company.email) : ""}
  </div>
  <div class="muted">Benfieg AI business report · generated ${esc(now.toLocaleString())}</div>
</header>

<h2>Question</h2>
<div class="q">${esc(r.question)}</div>

<h2>Analysis</h2>
<div class="answer">${esc(r.answer)}</div>
${actions}

${sources ? `<h2>Data sources used</h2><ul>${sources}</ul>` : ""}

<footer>
  ${esc(r.disclaimer)}<br>
  Generated by Benfieg via ${esc(r.provider)}${r.model ? " · " + esc(r.model) : ""}. All money in Nigerian Naira (₦).
</footer>
<script>window.onload = () => { window.print(); };</script>
</body></html>`;

  const w = window.open("", "_blank");
  if (!w) {
    alert("Please allow pop-ups to export the report as PDF.");
    return;
  }
  w.document.open();
  w.document.write(html);
  w.document.close();
}
