"""stock lot shipment ref and vessel

Revision ID: 00acb9f5a915
Revises: 4b2657e377af
Create Date: 2026-09-14 14:18:56.298881
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '00acb9f5a915'
down_revision: Union[str, None] = '4b2657e377af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_lots', sa.Column('shipment_ref', sa.String(length=255), nullable=True))
    op.add_column('stock_lots', sa.Column('vessel_mmsi', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_lots', 'vessel_mmsi')
    op.drop_column('stock_lots', 'shipment_ref')
    # ### end Alembic commands ###
