"""company_profile

Revision ID: 00f3c35a76a5
Revises: 6a31a0445b19
Create Date: 2026-09-14 17:50:16.442135
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '00f3c35a76a5'
down_revision: Union[str, None] = '6a31a0445b19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_profile',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('tax_id', sa.String(length=64), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('footer_note', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_profile')
    # ### end Alembic commands ###
