"""product substitutes

Revision ID: 0b4110206390
Revises: 8e92c86104ab
Create Date: 2026-09-16 00:10:58.138253
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0b4110206390'
down_revision: Union[str, None] = '8e92c86104ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_substitutes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('substitute_id', sa.Integer(), nullable=False),
    sa.Column('preference_rank', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_origin', sa.String(length=32), nullable=False),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('extraction_method', sa.String(length=64), nullable=True),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('verified_by_id', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['substitute_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_substitutes_data_origin'), 'product_substitutes', ['data_origin'], unique=False)
    op.create_index(op.f('ix_product_substitutes_product_id'), 'product_substitutes', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_substitutes_substitute_id'), 'product_substitutes', ['substitute_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_substitutes_substitute_id'), table_name='product_substitutes')
    op.drop_index(op.f('ix_product_substitutes_product_id'), table_name='product_substitutes')
    op.drop_index(op.f('ix_product_substitutes_data_origin'), table_name='product_substitutes')
    op.drop_table('product_substitutes')
    # ### end Alembic commands ###
