"""notification category severity link

Revision ID: 10ffde3f9ac2
Revises: 164931ee3acc
Create Date: 2026-09-12 11:12:29.312196
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '10ffde3f9ac2'
down_revision: Union[str, None] = '164931ee3acc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('category', sa.String(length=64), nullable=False))
    op.add_column('notifications', sa.Column('severity', sa.String(length=16), nullable=False))
    op.add_column('notifications', sa.Column('link', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_notifications_category'), 'notifications', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_category'), table_name='notifications')
    op.drop_column('notifications', 'link')
    op.drop_column('notifications', 'severity')
    op.drop_column('notifications', 'category')
    # ### end Alembic commands ###
