"""phase5 extracted_invoices

Revision ID: 164931ee3acc
Revises: 74b07f423c63
Create Date: 2026-09-11 23:56:22.465857
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '164931ee3acc'
down_revision: Union[str, None] = '74b07f423c63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extracted_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('data_import_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('overall_confidence', sa.Float(), nullable=True),
    sa.Column('extracted', sa.JSON(), nullable=False),
    sa.Column('matched', sa.JSON(), nullable=False),
    sa.Column('validation', sa.JSON(), nullable=False),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('created_invoice_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_invoices_data_import_id'), 'extracted_invoices', ['data_import_id'], unique=False)
    op.create_index(op.f('ix_extracted_invoices_document_id'), 'extracted_invoices', ['document_id'], unique=False)
    op.create_index(op.f('ix_extracted_invoices_status'), 'extracted_invoices', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extracted_invoices_status'), table_name='extracted_invoices')
    op.drop_index(op.f('ix_extracted_invoices_document_id'), table_name='extracted_invoices')
    op.drop_index(op.f('ix_extracted_invoices_data_import_id'), table_name='extracted_invoices')
    op.drop_table('extracted_invoices')
    # ### end Alembic commands ###
