"""invoice shipping

Revision ID: 397f21cfc00d
Revises: 00f3c35a76a5
Create Date: 2026-09-14 17:56:11.351348
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '397f21cfc00d'
down_revision: Union[str, None] = '00f3c35a76a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('shipping', sa.Numeric(precision=16, scale=2), nullable=False, server_default='0'))
    op.add_column('invoices', sa.Column('shipping_note', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'shipping_note')
    op.drop_column('invoices', 'shipping')
    # ### end Alembic commands ###
