"""product image_url

Revision ID: 58c2eade15be
Revises: 397f21cfc00d
Create Date: 2026-09-14 18:09:25.691351
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '58c2eade15be'
down_revision: Union[str, None] = '397f21cfc00d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_url', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image_url')
    # ### end Alembic commands ###
