"""invoice governance: created_by, version_no, invoice_versions

Revision ID: 6a31a0445b19
Revises: 00acb9f5a915
Create Date: 2026-09-14 14:35:57.612019
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6a31a0445b19'
down_revision: Union[str, None] = '00acb9f5a915'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('change_note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_versions_created_at'), 'invoice_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_invoice_versions_invoice_id'), 'invoice_versions', ['invoice_id'], unique=False)
    op.add_column('invoices', sa.Column('created_by_user_id', sa.Integer(), nullable=True))
    op.add_column('invoices', sa.Column('updated_by_user_id', sa.Integer(), nullable=True))
    op.add_column('invoices', sa.Column('version_no', sa.Integer(), nullable=False,
                                        server_default='1'))
    op.create_index(op.f('ix_invoices_created_by_user_id'), 'invoices', ['created_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_created_by_user_id'), table_name='invoices')
    op.drop_column('invoices', 'version_no')
    op.drop_column('invoices', 'updated_by_user_id')
    op.drop_column('invoices', 'created_by_user_id')
    op.drop_index(op.f('ix_invoice_versions_invoice_id'), table_name='invoice_versions')
    op.drop_index(op.f('ix_invoice_versions_created_at'), table_name='invoice_versions')
    op.drop_table('invoice_versions')
    # ### end Alembic commands ###
