"""initial schema

Revision ID: 74b07f423c63
Revises: 
Create Date: 2026-09-11 12:59:00.497672
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '74b07f423c63'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('data_origin', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_category'), 'alerts', ['category'], unique=False)
    op.create_index(op.f('ix_alerts_data_origin'), 'alerts', ['data_origin'], unique=False)
    op.create_index(op.f('ix_alerts_is_resolved'), 'alerts', ['is_resolved'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('opened_on', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branches_code'), 'branches', ['code'], unique=True)
    op.create_table('business_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_events_event_date'), 'business_events', ['event_date'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=64), nullable=True),
    sa.Column('customer_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('first_purchase_date', sa.Date(), nullable=True),
    sa.Column('last_purchase_date', sa.Date(), nullable=True),
    sa.Column('acquisition_date', sa.Date(), nullable=True),
    sa.Column('lifetime_revenue', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('lifetime_gross_profit', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('order_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_origin', sa.String(length=32), nullable=False),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('extraction_method', sa.String(length=64), nullable=True),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('verified_by_id', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_code'), 'customers', ['code'], unique=True)
    op.create_index(op.f('ix_customers_data_origin'), 'customers', ['data_origin'], unique=False)
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    op.create_index(op.f('ix_customers_status'), 'customers', ['status'], unique=False)
    op.create_table('data_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=512), nullable=True),
    sa.Column('file_format', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('rows_total', sa.Integer(), nullable=True),
    sa.Column('rows_imported', sa.Integer(), nullable=True),
    sa.Column('rows_failed', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('data_import_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('economic_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicator', sa.String(length=64), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_origin', sa.String(length=32), nullable=False),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('extraction_method', sa.String(length=64), nullable=True),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('verified_by_id', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_economic_data_data_origin'), 'economic_data', ['data_origin'], unique=False)
    op.create_index(op.f('ix_economic_data_indicator'), 'economic_data', ['indicator'], unique=False)
    op.create_index(op.f('ix_economic_data_period'), 'economic_data', ['period'], unique=False)
    op.create_table('market_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('relevance', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_origin', sa.String(length=32), nullable=False),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('extraction_method', sa.String(length=64), nullable=True),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('verified_by_id', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_events_data_origin'), 'market_events', ['data_origin'], unique=False)
    op.create_index(op.f('ix_market_events_event_date'), 'market_events', ['event_date'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('owner_knowledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('related_entity_type', sa.String(length=64), nullable=True),
    sa.Column('related_entity_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owner_knowledge_topic'), 'owner_knowledge', ['topic'], unique=False)
    op.create_table('simulation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('scenario_type', sa.String(length=64), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('assumptions', sa.JSON(), nullable=False),
    sa.Column('horizon_months', sa.Integer(), nullable=False),
    sa.Column('iterations', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('input_data_version', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_runs_scenario_type'), 'simulation_runs', ['scenario_type'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_terms', sa.String(length=64), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_origin', sa.String(length=32), nullable=False),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('extraction_method', sa.String(length=64), nullable=True),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('verified_by_id', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_code'), 'suppliers', ['code'], unique=True)
    op.create_index(op.f('ix_suppliers_data_origin'), 'suppliers', ['data_origin'], unique=False)
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=False)
    op.create_index(op.f('ix_suppliers_status'), 'suppliers', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role_title', sa.String(length=128), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('monthly_cost', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('hired_on', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_code'), 'employees', ['code'], unique=True)
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_origin', sa.String(length=32), nullable=False),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('extraction_method', sa.String(length=64), nullable=True),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('verified_by_id', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_category'), 'expenses', ['category'], unique=False)
    op.create_index(op.f('ix_expenses_data_origin'), 'expenses', ['data_origin'], unique=False)
    op.create_index(op.f('ix_expenses_expense_date'), 'expenses', ['expense_date'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=64), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('data_import_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_origin', sa.String(length=32), nullable=False),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('extraction_method', sa.String(length=64), nullable=True),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('verified_by_id', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['data_import_id'], ['data_imports.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_customer_id'), 'invoices', ['customer_id'], unique=False)
    op.create_index(op.f('ix_invoices_data_origin'), 'invoices', ['data_origin'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_date'), 'invoices', ['invoice_date'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('part_number', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('manufacturer', sa.String(length=128), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('purchase_cost', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('selling_price', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('reorder_level', sa.Integer(), nullable=True),
    sa.Column('reorder_quantity', sa.Integer(), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_origin', sa.String(length=32), nullable=False),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('extraction_method', sa.String(length=64), nullable=True),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('verified_by_id', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_code'), 'products', ['code'], unique=True)
    op.create_index(op.f('ix_products_data_origin'), 'products', ['data_origin'], unique=False)
    op.create_index(op.f('ix_products_is_active'), 'products', ['is_active'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_part_number'), 'products', ['part_number'], unique=False)
    op.create_table('purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_origin', sa.String(length=32), nullable=False),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('extraction_method', sa.String(length=64), nullable=True),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('verified_by_id', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchases_data_origin'), 'purchases', ['data_origin'], unique=False)
    op.create_index(op.f('ix_purchases_purchase_date'), 'purchases', ['purchase_date'], unique=False)
    op.create_index(op.f('ix_purchases_reference'), 'purchases', ['reference'], unique=False)
    op.create_index(op.f('ix_purchases_supplier_id'), 'purchases', ['supplier_id'], unique=False)
    op.create_table('simulation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('metric', sa.String(length=128), nullable=False),
    sa.Column('baseline', sa.JSON(), nullable=True),
    sa.Column('scenario', sa.JSON(), nullable=True),
    sa.Column('delta', sa.JSON(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_results_metric'), 'simulation_results', ['metric'], unique=False)
    op.create_index(op.f('ix_simulation_results_run_id'), 'simulation_results', ['run_id'], unique=False)
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('quantity_on_hand', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('safety_stock', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_origin', sa.String(length=32), nullable=False),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('extraction_method', sa.String(length=64), nullable=True),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('verified_by_id', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'branch_id', name='uq_inventory_product_branch')
    )
    op.create_index(op.f('ix_inventory_data_origin'), 'inventory', ['data_origin'], unique=False)
    op.create_index(op.f('ix_inventory_product_id'), 'inventory', ['product_id'], unique=False)
    op.create_table('invoice_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('original_description', sa.String(length=512), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_origin', sa.String(length=32), nullable=False),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('extraction_method', sa.String(length=64), nullable=True),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('verified_by_id', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_lines_data_origin'), 'invoice_lines', ['data_origin'], unique=False)
    op.create_index(op.f('ix_invoice_lines_invoice_id'), 'invoice_lines', ['invoice_id'], unique=False)
    op.create_table('product_price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('purchase_cost', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('selling_price', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_price_history_product_id'), 'product_price_history', ['product_id'], unique=False)
    op.create_table('purchase_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('original_description', sa.String(length=512), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_origin', sa.String(length=32), nullable=False),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('extraction_method', sa.String(length=64), nullable=True),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('verified_by_id', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_lines_data_origin'), 'purchase_lines', ['data_origin'], unique=False)
    op.create_index(op.f('ix_purchase_lines_purchase_id'), 'purchase_lines', ['purchase_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_lines_purchase_id'), table_name='purchase_lines')
    op.drop_index(op.f('ix_purchase_lines_data_origin'), table_name='purchase_lines')
    op.drop_table('purchase_lines')
    op.drop_index(op.f('ix_product_price_history_product_id'), table_name='product_price_history')
    op.drop_table('product_price_history')
    op.drop_index(op.f('ix_invoice_lines_invoice_id'), table_name='invoice_lines')
    op.drop_index(op.f('ix_invoice_lines_data_origin'), table_name='invoice_lines')
    op.drop_table('invoice_lines')
    op.drop_index(op.f('ix_inventory_product_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_data_origin'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_simulation_results_run_id'), table_name='simulation_results')
    op.drop_index(op.f('ix_simulation_results_metric'), table_name='simulation_results')
    op.drop_table('simulation_results')
    op.drop_index(op.f('ix_purchases_supplier_id'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_reference'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_purchase_date'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_data_origin'), table_name='purchases')
    op.drop_table('purchases')
    op.drop_index(op.f('ix_products_part_number'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_is_active'), table_name='products')
    op.drop_index(op.f('ix_products_data_origin'), table_name='products')
    op.drop_index(op.f('ix_products_code'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_date'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_data_origin'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_customer_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_expenses_expense_date'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_data_origin'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_category'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_employees_code'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_suppliers_status'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_data_origin'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_code'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_simulation_runs_scenario_type'), table_name='simulation_runs')
    op.drop_table('simulation_runs')
    op.drop_index(op.f('ix_owner_knowledge_topic'), table_name='owner_knowledge')
    op.drop_table('owner_knowledge')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_market_events_event_date'), table_name='market_events')
    op.drop_index(op.f('ix_market_events_data_origin'), table_name='market_events')
    op.drop_table('market_events')
    op.drop_index(op.f('ix_economic_data_period'), table_name='economic_data')
    op.drop_index(op.f('ix_economic_data_indicator'), table_name='economic_data')
    op.drop_index(op.f('ix_economic_data_data_origin'), table_name='economic_data')
    op.drop_table('economic_data')
    op.drop_table('documents')
    op.drop_table('data_sources')
    op.drop_table('data_imports')
    op.drop_index(op.f('ix_customers_status'), table_name='customers')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_data_origin'), table_name='customers')
    op.drop_index(op.f('ix_customers_code'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_business_events_event_date'), table_name='business_events')
    op.drop_table('business_events')
    op.drop_index(op.f('ix_branches_code'), table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_is_resolved'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_data_origin'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_category'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
