"""supplier payments and payables

Revision ID: a8bbe1d7ce14
Revises: 5eae7bb0795e
Create Date: 2026-09-16 02:39:31.420469
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a8bbe1d7ce14'
down_revision: Union[str, None] = '5eae7bb0795e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('reference', sa.String(length=128), nullable=True),
    sa.Column('paid_at', sa.Date(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('recorded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_origin', sa.String(length=32), nullable=False),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('extraction_method', sa.String(length=64), nullable=True),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('verified_by_id', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_payments_data_origin'), 'supplier_payments', ['data_origin'], unique=False)
    op.create_index(op.f('ix_supplier_payments_paid_at'), 'supplier_payments', ['paid_at'], unique=False)
    op.create_index(op.f('ix_supplier_payments_purchase_id'), 'supplier_payments', ['purchase_id'], unique=False)
    op.create_index(op.f('ix_supplier_payments_status'), 'supplier_payments', ['status'], unique=False)
    op.create_index(op.f('ix_supplier_payments_supplier_id'), 'supplier_payments', ['supplier_id'], unique=False)
    op.add_column('purchases', sa.Column('amount_paid', sa.Numeric(precision=16, scale=2),
                  nullable=False, server_default='0'))
    op.add_column('purchases', sa.Column('payment_status', sa.String(length=16),
                  nullable=False, server_default='UNPAID'))
    op.add_column('purchases', sa.Column('due_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_purchases_due_date'), 'purchases', ['due_date'], unique=False)
    op.create_index(op.f('ix_purchases_payment_status'), 'purchases', ['payment_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchases_payment_status'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_due_date'), table_name='purchases')
    op.drop_column('purchases', 'due_date')
    op.drop_column('purchases', 'payment_status')
    op.drop_column('purchases', 'amount_paid')
    op.drop_index(op.f('ix_supplier_payments_supplier_id'), table_name='supplier_payments')
    op.drop_index(op.f('ix_supplier_payments_status'), table_name='supplier_payments')
    op.drop_index(op.f('ix_supplier_payments_purchase_id'), table_name='supplier_payments')
    op.drop_index(op.f('ix_supplier_payments_paid_at'), table_name='supplier_payments')
    op.drop_index(op.f('ix_supplier_payments_data_origin'), table_name='supplier_payments')
    op.drop_table('supplier_payments')
    # ### end Alembic commands ###
