"""vessel_tracks persistence

Revision ID: d51ff1fb37b0
Revises: 10ffde3f9ac2
Create Date: 2026-09-14 13:28:03.400383
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd51ff1fb37b0'
down_revision: Union[str, None] = '10ffde3f9ac2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vessel_tracks',
    sa.Column('mmsi', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('sog', sa.Float(), nullable=True),
    sa.Column('cog', sa.Float(), nullable=True),
    sa.Column('ship_type', sa.Integer(), nullable=True),
    sa.Column('destination', sa.String(length=120), nullable=True),
    sa.Column('eta', sa.String(length=40), nullable=True),
    sa.Column('region', sa.String(length=48), nullable=False),
    sa.Column('origin_region', sa.String(length=48), nullable=True),
    sa.Column('bound_for_nigeria', sa.Boolean(), nullable=False),
    sa.Column('arrived_nigeria', sa.Boolean(), nullable=False),
    sa.Column('first_seen', sa.String(length=40), nullable=True),
    sa.Column('last_seen', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('mmsi')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vessel_tracks')
    # ### end Alembic commands ###
