"""payment bank transfer details

Revision ID: f286730f0543
Revises: a8bbe1d7ce14
Create Date: 2026-09-16 12:25:42.591453
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f286730f0543'
down_revision: Union[str, None] = 'a8bbe1d7ce14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('txid', sa.String(length=128), nullable=True))
    op.add_column('payments', sa.Column('from_account', sa.String(length=64), nullable=True))
    op.add_column('payments', sa.Column('from_name', sa.String(length=128), nullable=True))
    op.add_column('payments', sa.Column('to_account', sa.String(length=64), nullable=True))
    op.add_column('payments', sa.Column('to_name', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_payments_txid'), 'payments', ['txid'], unique=False)
    op.add_column('supplier_payments', sa.Column('txid', sa.String(length=128), nullable=True))
    op.add_column('supplier_payments', sa.Column('from_account', sa.String(length=64), nullable=True))
    op.add_column('supplier_payments', sa.Column('from_name', sa.String(length=128), nullable=True))
    op.add_column('supplier_payments', sa.Column('to_account', sa.String(length=64), nullable=True))
    op.add_column('supplier_payments', sa.Column('to_name', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_supplier_payments_txid'), 'supplier_payments', ['txid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supplier_payments_txid'), table_name='supplier_payments')
    op.drop_column('supplier_payments', 'to_name')
    op.drop_column('supplier_payments', 'to_account')
    op.drop_column('supplier_payments', 'from_name')
    op.drop_column('supplier_payments', 'from_account')
    op.drop_column('supplier_payments', 'txid')
    op.drop_index(op.f('ix_payments_txid'), table_name='payments')
    op.drop_column('payments', 'to_name')
    op.drop_column('payments', 'to_account')
    op.drop_column('payments', 'from_name')
    op.drop_column('payments', 'from_account')
    op.drop_column('payments', 'txid')
    # ### end Alembic commands ###
